"""
ApplicationStatus Model - Represents a valid application status (reference data).
"""

from dataclasses import dataclass
from typing import Optional
from job_tracker.models.base import BaseModel, ValidationError

# Single source of truth for the application status state machine.
# To add a new status: add one entry here. Everything else derives from this.
STATUS_MACHINE: dict[str, dict] = {
    "Applied":             {"is_terminal": False, "transitions": {"Interview Scheduled", "Rejected", "Withdrawn"}},
    "Interview Scheduled": {"is_terminal": False, "transitions": {"Interviewed", "Rejected"}},
    "Interviewed":         {"is_terminal": False, "transitions": {"Offer", "Rejected"}},
    "Offer":               {"is_terminal": False, "transitions": {"Accepted", "Rejected", "Withdrawn"}},
    "Accepted":            {"is_terminal": True,  "transitions": set()},
    "Rejected":            {"is_terminal": True,  "transitions": set()},
    "Withdrawn":           {"is_terminal": True,  "transitions": set()},
}

# Derived view kept for backwards compatibility with any direct callers.
VALID_STATUSES = {name: info["is_terminal"] for name, info in STATUS_MACHINE.items()}


@dataclass
class ApplicationStatus(BaseModel):
    """
    Represents a valid application status (reference data).

    This table contains the list of valid statuses that applications can be in.
    Terminal states (Accepted, Rejected, Withdrawn) cannot transition to other states.

    Attributes:
        id: Unique identifier (auto-generated by database, optional)
        status_name: Status name (required, unique, max 50 chars)
        description: Status description (optional, max 255 chars)
        is_terminal: Whether this is a final state (required)

    Valid Statuses:
        - Applied (not terminal)
        - Interview Scheduled (not terminal)
        - Interviewed (not terminal)
        - Offer (not terminal)
        - Accepted (terminal)
        - Rejected (terminal)
        - Withdrawn (terminal)
    """

    id: Optional[int] = None
    status_name: str = ""
    description: Optional[str] = None
    is_terminal: bool = False

    def validate(self) -> None:
        """
        Validate status data.

        Rules:
        - status_name: Required, non-empty, max 50 chars, must be in VALID_STATUSES
        - description: Max 255 chars if provided
        - is_terminal: Must match the expected value for the status_name

        Raises:
            ValidationError: If validation fails
        """
        if not self.status_name or not self.status_name.strip():
            raise ValidationError("Status name is required")

        if len(self.status_name) > 50:
            raise ValidationError("Status name cannot exceed 50 characters")

        if self.status_name not in STATUS_MACHINE:
            raise ValidationError(f"Invalid status '{self.status_name}'. Valid statuses: {', '.join(STATUS_MACHINE.keys())}")

        expected_terminal = STATUS_MACHINE[self.status_name]["is_terminal"]
        if self.is_terminal != expected_terminal:
            raise ValidationError(f"Status '{self.status_name}' should have is_terminal={expected_terminal}")

        if self.description and len(self.description) > 255:
            raise ValidationError("Description cannot exceed 255 characters")

    def is_final_state(self) -> bool:
        """
        Check if this is a terminal/final state.

        Returns:
            True if this is a terminal state, False otherwise
        """
        return self.is_terminal

    def __str__(self) -> str:
        """
        Return user-friendly string representation.

        Returns:
            Status name
        """
        return self.status_name

