"""
ApplicationEvent Model - Represents an event in an application timeline (immutable audit log).
"""

from dataclasses import dataclass
from typing import Optional
from datetime import datetime
from job_tracker.models.base import BaseModel, ValidationError

@dataclass
class ApplicationEvent(BaseModel):
    """
    Represents an event in an application timeline (immutable audit log).

    This is an append-only log - events cannot be updated or deleted.

    Attributes:
        id: Unique identifier (auto-generated by database, optional)
        application_id: Foreign key to application (required)
        event_type: Type of event (required, max 50 chars)
        event_date: When the event occurred (required, not in future)
        notes: Event details (optional, max 255 chars)
        created_at: Timestamp when created
    """

    id: Optional[int] = None
    application_id: int = 0
    event_type: str = ""
    event_date: Optional[datetime] = None
    notes: Optional[str] = None
    created_at: Optional[datetime] = None

    def validate(self) -> None:
        """
        Validate event data.

        Rules:
        - application_id: Required, must be positive
        - event_type: Required, non-empty, max 50 chars
        - event_date: Required, not in future
        - notes: Max 255 chars if provided

        Raises:
            ValidationError: If validation fails
        """
        if self.application_id <= 0:
            raise ValidationError("Application ID is required and must be positive")

        if not self.event_type or not self.event_type.strip():
            raise ValidationError("Event type is required")

        if len(self.event_type) > 50:
            raise ValidationError("Event type cannot exceed 50 characters")

        if self.event_date is None:
            raise ValidationError("Event date is required")

        # Handle string dates
        if isinstance(self.event_date, str):
            try:
                self.event_date = datetime.fromisoformat(self.event_date)
            except ValueError:
                raise ValidationError(f"Invalid date format: {self.event_date}")

        # Strip timezone before comparing so offset-aware DB timestamps work alongside
        # naive datetime.now().  Both sides are treated as UTC.
        event_date_naive = self.event_date.replace(tzinfo=None)
        if event_date_naive > datetime.now():
            raise ValidationError(f"Event date cannot be in the future: {self.event_date}")

        if self.notes and len(self.notes) > 255:
            raise ValidationError("Notes cannot exceed 255 characters")


