"""
Application Model - Represents a job application.
"""

from dataclasses import dataclass
from typing import Optional
from datetime import date, datetime
from job_tracker.models.base import BaseModel, ValidationError


@dataclass
class Application(BaseModel):
    """
    Represents a job application.

    Attributes:
        id: Unique identifier (auto-generated by database, optional)
        company_id: Foreign key to company (required)
        position_id: Foreign key to position (required)
        recruiter_id: Foreign key to recruiter (optional)
        current_status: Foreign key to application_status (required)
        applied_date: Date application was submitted (required, not in future, within 365 days)
        notes: Additional notes (optional, max 255 chars)
        created_at: Timestamp when created
        updated_at: Timestamp when last updated
    """

    id: Optional[int] = None
    company_id: int = 0
    position_id: int = 0
    recruiter_id: Optional[int] = None
    current_status: int = 0
    applied_date: Optional[date] = None
    notes: Optional[str] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None

    def validate(self) -> None:
        """
        Validate application data.

        Rules:
        - company_id: Required, must be positive
        - position_id: Required, must be positive
        - current_status: Required, must be positive
        - applied_date: Required, not in future, within last 365 days
        - notes: Max 255 chars if provided

        Raises:
            ValidationError: If validation fails
        """
        if self.company_id <= 0:
            raise ValidationError("Company ID is required and must be positive")

        if self.position_id <= 0:
            raise ValidationError("Position ID is required and must be positive")

        if self.current_status <= 0:
            raise ValidationError("Status is required and must be positive")

        if self.applied_date is None:
            raise ValidationError("Applied date is required")

        if isinstance(self.applied_date, str):
            try:
                self.applied_date = datetime.strptime(self.applied_date, "%Y-%m-%d").date()
            except ValueError:
                raise ValidationError(f"Invalid date format: {self.applied_date}. Use YYYY-MM-DD")

        if self.applied_date > date.today():
            raise ValidationError(f"Applied date cannot be in the future: {self.applied_date}")

        days_diff = (date.today() - self.applied_date).days
        if days_diff > 365:
            raise ValidationError(f"Applied date must be within last 365 days (was {days_diff} days ago)")

        # Check notes length
        if self.notes and len(self.notes) > 255:
            raise ValidationError("Notes cannot exceed 255 characters")

    def to_dict(self) -> dict:
        """
        Serialize application to dictionary.

        Returns:
            Dictionary representation
        """
        return {
            'id': self.id,
            'company_id': self.company_id,
            'position_id': self.position_id,
            'recruiter_id': self.recruiter_id,
            'current_status': self.current_status,
            'applied_date': self.applied_date,
            'notes': self.notes,
            'created_at': self.created_at,
            'updated_at': self.updated_at
        }

    @classmethod
    def from_dict(cls, data: dict) -> 'Application':
        """
        Deserialize application from dictionary.

        Args:
            data: Dictionary with application data

        Returns:
            Application instance

        Raises:
            ValidationError: If validation fails
        """
        try:
            instance = cls(**data)
            instance.validate()
            return instance
        except TypeError as e:
            raise ValidationError(f"Invalid data for Application: {e}")
        except ValidationError:
            raise

    def days_in_current_status(self) -> int:
        """
        Calculate how many days the application has been in current status.

        Returns:
            Number of days since creation
        """
        if self.created_at is None:
            return 0
        created_date = self.created_at.date() if isinstance(self.created_at, datetime) else self.created_at
        return (date.today() - created_date).days

