"""
Company Model - Represents a company/employer in the job tracker.
"""

from dataclasses import dataclass
from typing import Optional
from datetime import datetime
from job_tracker.models.base import BaseModel, ValidationError


@dataclass
class Company(BaseModel):
    """
    Represents a company in the job application tracker.

    Attributes:
        id: Unique identifier (auto-generated by database, optional)
        name: Company name (required, unique, max 50 chars)
        industry: Industry sector (optional, max 50 chars)
        location: Geographic location (optional, max 50 chars)
        notes: Additional notes (optional, max 255 chars)
        created_at: Timestamp when created
        updated_at: Timestamp when last updated
    """

    id: Optional[int] = None
    name: str = ""
    industry: Optional[str] = None
    location: Optional[str] = None
    notes: Optional[str] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None

    def validate(self) -> None:
        """
        Validate company data.

        Rules:
        - name: Required, non-empty, max 50 chars
        - location: Optional, max 50 chars if provided
        - industry: Must be non-empty if provided, max 50 chars
        - notes: Max 255 chars if provided

        Raises:
            ValidationError: If validation fails
        """
        if not self.name or not self.name.strip():
            raise ValidationError("Company name is required and cannot be empty")

        if len(self.name) > 50:
            raise ValidationError("Company name cannot exceed 50 characters")

        if self.location is not None:
            if not self.location.strip():
                raise ValidationError("Location cannot be empty if provided")
            if len(self.location) > 50:
                raise ValidationError("Location cannot exceed 50 characters")

        if self.industry is not None:
            if not self.industry.strip():
                raise ValidationError("Industry cannot be empty if provided")
            if len(self.industry) > 50:
                raise ValidationError("Industry cannot exceed 50 characters")

        if self.notes is not None:
            if len(self.notes) > 255:
                raise ValidationError("Notes cannot exceed 255 characters")

    def to_dict(self) -> dict:
        """
        Serialize company to dictionary.

        Returns:
            Dictionary representation
        """
        return {
            'id': self.id,
            'name': self.name,
            'industry': self.industry,
            'location': self.location,
            'notes': self.notes,
            'created_at': self.created_at,
            'updated_at': self.updated_at
        }

    @classmethod
    def from_dict(cls, data: dict) -> 'Company':
        """
        Deserialize company from dictionary.

        Args:
            data: Dictionary with company data

        Returns:
            Company instance

        Raises:
            ValidationError: If validation fails
        """
        try:
            instance = cls(**data)
            instance.validate()
            return instance
        except TypeError as e:
            raise ValidationError(f"Invalid data for Company: {e}")
        except ValidationError:
            raise

