"""
Position Model - Represents a job position/title in the job tracker.
"""

from dataclasses import dataclass
from typing import Optional
from datetime import datetime
from job_tracker.models.base import BaseModel, ValidationError

# Valid position levels
VALID_LEVELS = {"Entry", "Intern", "Junior", "Mid", "Senior", "Student", "Lead", "Manager"}


@dataclass
class Position(BaseModel):
    """
    Represents a job position/title.

    Attributes:
        id: Unique identifier (auto-generated by database, optional)
        title: Position title (required, max 50 chars)
        level: Seniority level (required, must be one of VALID_LEVELS)
        created_at: Timestamp when created

    Valid Levels: Entry, Intern, Junior, Mid, Senior, Student, Lead, Manager
    """

    id: Optional[int] = None
    title: str = ""
    level: str = ""
    created_at: Optional[datetime] = None

    def validate(self) -> None:
        """
        Validate position data.

        Rules:
        - title: Required, non-empty, max 50 chars
        - level: Required, must be one of VALID_LEVELS

        Raises:
            ValidationError: If validation fails
        """
        if not self.title or not self.title.strip():
            raise ValidationError("Position title is required")

        if len(self.title) > 50:
            raise ValidationError("Position title cannot exceed 50 characters")

        if self.level not in VALID_LEVELS:
            raise ValidationError(f"Invalid level '{self.level}'. Must be one of: {', '.join(sorted(VALID_LEVELS))}")


