"""
Position Model - Represents a job position/title in the job tracker.
"""

from dataclasses import dataclass
from typing import Optional
from datetime import datetime
from job_tracker.models.base import BaseModel, ValidationError

# Valid position levels
VALID_LEVELS = {"Entry", "Intern", "Junior", "Mid", "Senior", "Lead", "Manager"}


@dataclass
class Position(BaseModel):
    """
    Represents a job position/title.

    Attributes:
        id: Unique identifier (auto-generated by database, optional)
        title: Position title (required, max 50 chars)
        level: Seniority level (required, must be one of VALID_LEVELS)
        created_at: Timestamp when created

    Valid Levels: Entry, Intern, Junior, Mid, Senior, Lead, Manager
    """

    id: Optional[int] = None
    title: str = ""
    level: str = ""
    created_at: Optional[datetime] = None

    def validate(self) -> None:
        """
        Validate position data.

        Rules:
        - title: Required, non-empty, max 50 chars
        - level: Required, must be one of VALID_LEVELS

        Raises:
            ValidationError: If validation fails
        """
        if not self.title or not self.title.strip():
            raise ValidationError("Position title is required")

        if len(self.title) > 50:
            raise ValidationError("Position title cannot exceed 50 characters")

        if self.level not in VALID_LEVELS:
            raise ValidationError(f"Invalid level '{self.level}'. Must be one of: {', '.join(sorted(VALID_LEVELS))}")

    def to_dict(self) -> dict:
        """
        Serialize position to dictionary.

        Returns:
            Dictionary representation
        """
        return {
            'id': self.id,
            'title': self.title,
            'level': self.level,
            'created_at': self.created_at
        }

    @classmethod
    def from_dict(cls, data: dict) -> 'Position':
        """
        Deserialize position from dictionary.

        Args:
            data: Dictionary with position data

        Returns:
            Position instance

        Raises:
            ValidationError: If validation fails
        """
        try:
            instance = cls(**data)
            instance.validate()
            return instance
        except TypeError as e:
            raise ValidationError(f"Invalid data for Position: {e}")
        except ValidationError:
            raise

