"""
Recruiter Model - Represents a recruiter or reference contact.
"""

from dataclasses import dataclass
from typing import Optional
from datetime import datetime
import re
from job_tracker.models.base import BaseModel, ValidationError

EMAIL_REGEX = r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'


@dataclass
class Recruiter(BaseModel):
    """
    Represents a recruiter or reference contact.

    Attributes:
        id: Unique identifier (auto-generated by database, optional)
        name: Recruiter name (required, max 50 chars)
        email: Email address (optional, must be valid format if provided, unique, max 50 chars)
        phone: Phone number (optional, max 50 chars)
        company_id: Associated company (optional, foreign key)
        created_at: Timestamp when created
    """

    id: Optional[int] = None
    name: str = ""
    email: Optional[str] = None
    phone: Optional[str] = None
    company_id: Optional[int] = None
    created_at: Optional[datetime] = None

    def validate(self) -> None:
        """
        Validate recruiter data.

        Rules:
        - name: Required, non-empty, max 50 chars
        - email: If provided, must be valid email format, max 50 chars
        - phone: If provided, max 50 chars

        Raises:
            ValidationError: If validation fails
        """
        if not self.name or not self.name.strip():
            raise ValidationError("Recruiter name is required")

        if len(self.name) > 50:
            raise ValidationError("Recruiter name cannot exceed 50 characters")

        if self.email:
            if not re.match(EMAIL_REGEX, self.email):
                raise ValidationError(f"Invalid email format: {self.email}")
            if len(self.email) > 50:
                raise ValidationError("Email cannot exceed 50 characters")

        if self.phone:
            if len(self.phone) > 50:
                raise ValidationError("Phone cannot exceed 50 characters")

    def to_dict(self) -> dict:
        """
        Serialize recruiter to dictionary.

        Returns:
            Dictionary representation
        """
        return {
            'id': self.id,
            'name': self.name,
            'email': self.email,
            'phone': self.phone,
            'company_id': self.company_id,
            'created_at': self.created_at
        }

    @classmethod
    def from_dict(cls, data: dict) -> 'Recruiter':
        """
        Deserialize recruiter from dictionary.

        Args:
            data: Dictionary with recruiter data

        Returns:
            Recruiter instance

        Raises:
            ValidationError: If validation fails
        """
        try:
            instance = cls(**data)
            instance.validate()
            return instance
        except TypeError as e:
            raise ValidationError(f"Invalid data for Recruiter: {e}")
        except ValidationError:
            raise

